### ISSUE TITLE
Design (UX/UI) upgrade for the "Authorizations" page

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#1]
**Summary:**  
`In the application, we cannot conveniently use TextView (enriched text) as it is quite messy when displaying the HTML. "Authorizations" page was completely reviewed and new design was proposed to cover all possible situations. Hence, it is required to update design of the "Authorizations" page in both situations - with many "authorizations" available (swiping), and full screen authorization (when page is accessed from push-notification)`

**Actual behavior:**  
`TextView does not display the HTML styles properly on "Authorizations" page (as does the WebView) and this causes breach in the universality of the app` 

**Expected behavior:**  
`Design (UI/UX) should be updated according to the confirmed prototype`

**Materials:**  
*Prototype*  
https://projects.invisionapp.com/prototype/authentication-animation-cjyzm398p004nqn010nrwcgsf/play/053c9162  
*Figma files*  
https://www.figma.com/file/fFkej9m0LqBKhlnHSYhejv/New-Auth-Screens?node-id=1%3A912

**Task:**    
Remove TextView completely and keep WebView with new design for both states of the "Authorizations" page.  
- [x] 1) Adjust expanded "Authorization" page (accessible from push notification)
- [x] 2) Adjust simple "Authorizations" page with multiple `authorizations` available for confirmation (reached when user just opens the app)
- [x] 3) Remove the "refresh" button in top left corner please - it is unnecessary. as we refresh the content every 2 seconds.

___
Thanks!
