### ISSUE TITLE
Tab bar & "Authorizations" empty state adjustment

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#11]
**Summary:**  
`Design to be updated for best UX and consistency within apps`

**Materials:**  
Figma design file: https://www.figma.com/file/DUgnsLqq0Sg2sebofP61MZ/Auth-V2---iOS?node-id=0%3A1

**Task:**  
- [x] Tab bar has new icons, colors. Please adjust according to the design.
- [x] Change "Key" icon to the new one from design
- [x] Please rename the description to "You have no active authorizations. Once an action authorization is generated, it will be valid for a few minutes."

**Screenshots (if applicable)**  
![image](https://user-images.githubusercontent.com/38658558/64020217-b6164d00-cb39-11e9-8acd-7167c432b9ae.png)8
