### ISSUE TITLE
Design (UX/UI) upgrade for the "Connections" page

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#12]
**Summary:**  
`The "Connections" page requires some small adjustments to have a great user experience`

**Materials:**  
Figma design file: https://www.figma.com/file/DUgnsLqq0Sg2sebofP61MZ/Auth-V2---iOS?node-id=0%3A1

**Task:**  
*Screen 1:*
- [x] Rename title to `No Connections`
- [x] Rename description to "You have no currently connected service providers. Connect one to start receiving authorizations for your actions (e.g. payments)."
- [x] Change the "Bank" icon to the new one from design
- [x] Button should be named "Connect Provider"

*Screen 2:*
- [ ] Both, "Delete all" and "(+)"(add) buttons should be eliminated (logic to delete all app data is moved to Settings, button "clear all data", mentioned here: https://github.com/saltedge/sca-authenticator-ios/issues/14)
- [ ] Please adjust the Service Provider logo to fit the 48x48 placeholder. Please keep the grey background for the cases when Service Provider has smaller icon with transparent background, but just make the logo completely fit the round icon.
- [ ] The "(+)"(add) should be added as a floating button on the right-bottom corner (or in the middle) of the active screen, as in the design.
- [ ] Rename the inactive error message from "Inactive. Remove or reconnect." to "Inactive connection. Remove or reconnect."

*Screen 3:*
- [ ] Adjust the order and icons for the actions.
- [ ] Rename all options so they don't have word "Connection".

*Screen 4:*
- [ ] If connection is in "inactive" state, please add to the options the "Reconnect" button with new icon.
- [ ] The "Reconnect" button on tap is accessing the stored "connect_url", so user could authenticate and renew the connection.

*Additionally:*  
- [ ] "Rename connection" flow is fine, but please, when the length of the name is more than 30 symbols, for example, the name is going outside of the screen. It should be adjusted as in Android - three dots and space between the 3 dots and screen margin.

**Screenshots:**  
![image](https://user-images.githubusercontent.com/38658558/64859607-60f73280-d633-11e9-8339-d8c451df266e.png)

___
Thanks!

**Comment by AlexLobaciov** [comment]
outdated. closing.
