### ISSUE TITLE
Adjust the process of establishing new "connection"

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#13]
**Summary:**  
`On each step of adding new Service Provider (creating new "connection"), all the processes should be clear for user` 

**Materials:**  
Figma design file: https://www.figma.com/file/DUgnsLqq0Sg2sebofP61MZ/Auth-V2---iOS?node-id=0%3A1

**Task:**  
*Screen 1:*  
- [x] Please rename the action bar title to "Scan QR code"

*Screen 2:*  
While connection is in progress:
- [x] Action bar title should be "New connection". Keep it for next 2 screens (when user is reconnecting, please use "Reconnect" title in action bar).
~~- [ ] Spinner should be placed on top of action screen~~
~~- [ ] Title to be added, named "Connecting..."~~
~~- [ ] Description to be added, named "This may take some time. Please wait."~~

*Screen 3:*  
While user is in WebView, just keep the action bar same as previous

*Screen 4:*  
While user has successfully connected new Service Provider, please keep the action bar same as previous, and:
- [x] Please remove "Cancel" button from Action bar
- [x] Please update the "checkmark" icon
- [x] Title should be "{bank_name} was successfully connected!"
- [x] Description should be renamed to "Your Service Provider has been successfully connected to the Authenticator App. You will receive an authorization request every time you make an action."

**Screenshots (if applicable)**  
![image](https://user-images.githubusercontent.com/38658558/64353440-6edeff00-d006-11e9-9adc-386a1e0f4088.png)

**Comment by ConstantinKV** [comment]
@AlexLobaciov current spinner view is enough (corresponds iOS guides) to show asynchronous  connecting process.
