### ISSUE TITLE
Settings and "Change passcode" adjustment

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#14]
**Summary:**  
`Clear and convenient Settings to be in final product`

**Materials:**  
Figma design file: https://www.figma.com/file/DUgnsLqq0Sg2sebofP61MZ/Auth-V2---iOS?node-id=0%3A1

**Task:**  
- [x] Update settings page
Settings should have following structure:
- Block 1: Language
- Block 1: Passcode
- Block 1: Touch ID / Face ID
- Block 2: About
- Block 2: Report a bug (current: Contact Support)
Please adjust as in design.

When accessing Passcode:
- [x] Title change from "Passcode" to "Change Passcode"
- [ ] Rename "Enter Passcode" to "Input current passcode"
- [ ] Rename "Create Passcode" to "Input new passcode"
- [ ] Rename "Repeat Passcode" to "Repeat new passcode"

*Clear all data* button:  
- [x] New button to add in "Settings" - "Clear all data". Button is red, in 3rd - separate block in settings. Please verify design. The functionality will clean service providers as well as cache. The app should be clean, but PIN is left. After what user presses on "Clear all data" button, a confirmation step with Title "Delete all data?", description "All app data including service providers, user data and settings will be permanently deleted." and blue buttons "CANCEL" and "OK" is present. After what user presses "Submit" - all data is cleared.

**Screenshots (if applicable)**  
![image](https://user-images.githubusercontent.com/38658558/64028479-680a4500-cb4b-11e9-8224-83fb6c738c2c.png)

*Clear all data* screen:  
![image](https://user-images.githubusercontent.com/38658558/64854505-6ef28680-d626-11e9-808b-bbcf62d9cfb1.png)
