### ISSUE TITLE
Notifications access improvement

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#148]
**Summary:**  
For simplicity of the enabling notifications, it is necessary to add the notifications toggle which will enable notifications or disable them. Also, we have to ask for Notifications access below QR scan.

**Task:**  
- [x] Add to Settings new field "Enable notifications". Field is visible only when notifications are disabled for the app.
- [x] Please add a space between the last field in Settings and "Clear all data". Clear all data functionality should be displayed a little apart from the main settings.
- [x] Ask user to "Allow notifications" (show system dialogue) before the QR scan question to allow access to the camera. For now we will keep it without a separate page to allow notifications. We'll design and add this type of page later.

![image](https://user-images.githubusercontent.com/38658558/86806718-cd8b6400-c081-11ea-85b9-2aa13ff76193.png)

___

Thanks!
