### ISSUE TITLE
App setup improvement

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#18]
**Summary:**  
`UX and styles improvement`

**Materials:**  
Design - https://www.figma.com/file/DUgnsLqq0Sg2sebofP61MZ/Auth-V2---iOS?node-id=0%3A620  

**Task:**  
- [x] First screenshot (2) - please update the icon, there is a new one - instead of card there is the phone.
- [x] First screenshot (3) - to update title text to "One App for all Payment Accounts"
- [x] First screenshot (3) - to update description text to "Simply connect your Provider to the Authenticator to never worry about the security of your transactions again."
- [x] First screenshot -  For all "Getting started" screens - join the icon, title and description in 1 block. This block should be in the middle in regards to the Status bar and Page controls.
- [x] Second screenshot - For "App setup" - please keep the Title + Description place in regards to the progress line, but the Icon should be centered, so it's always in the center on the screen.
- [x] Second screenshot  - On "Well done!" screen, please leave button "Proceed" - the same size and on the same level as previous button (e.g. "Allow notifications"). There should be no automatic switch to "Connections" page. Please update the description text to "Application has been successfully set. Proceed to connect your service provider."

**Screenshots:**  

![image](https://user-images.githubusercontent.com/38658558/64173198-67312600-ce5f-11e9-9939-21b4f8b96530.png)

![image](https://user-images.githubusercontent.com/38658558/65585431-1f4b7d80-df8b-11e9-98a9-72066651f104.png)

**Comment by AlexLobaciov** [comment]
@ConstantinKV additional tasks were added after what some decisions were made for Android version. Please proceed.

**Comment by AlexLobaciov** [comment]
@baller784 Please update the text on last screen. Thanks!
