### ISSUE TITLE
Instant action implementation

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#62]
**Summary:**  
With introduced “Instant action” the app should have additional logic to proceed with user authentication, select the necessary provider and catch the redirect deep link.

Related issue: https://github.com/saltedge/sca-identity-service-example/issues/8

**Task:**
- [ ] Screen 1,2: Add a “QR code” icon - button to tap and scan QR code for “instant action”. Button should be added on top right corner of the “Authorizations” page.
- [ ] Screen 4: Add a new processing window with loading spinner and title “Authenticating for action”, with description "This may take some time. Please wait.".
- [ ] Screen 3: In case there are 2 similar connected accounts, the app will have to ask user which exactly account to choose. Please add the "Choose connection" page after what QR code is scanned and app does not know which connection to choose.
- [ ] Screen 5,6: If SCA is NOT required for specific action = the app should show final status with title “Successful action” and description “Action was successfully processed”. If flow ends up with an error - final status should be “Action error” and description “Please try again”  
- [ ] If SCA IS required then from loading screen (screen 3) user should get directly to the “Authorization request” screen (specific authorization from the list).  
- [ ] Realize the API endpoint to make a signed POST request to transmit to the Identity Service by the “action_url” the “action_id” and “access_token”.
- [ ] Receive in response to the previous action the result “OK”/”Error”, and if successful, then to proceed with the received “authorization_id”.
- [ ] If user scans QR code and app could not find the service provider, app should show error "Provider not found. Please create connection to your service provider and try again.".

**Design:**  
https://www.figma.com/file/Di0VLVeodXE7QmkmIiGKoX/Authenticator-iOS?node-id=369%3A5

![image](https://user-images.githubusercontent.com/38658558/74140576-fa843980-4bfd-11ea-824d-9abed73d9818.png)

**Comment by AlexLobaciov** [comment]
@baller784 please check the namings, they were adjusted. Thanks!
