### ISSUE TITLE
Additional parameters to add to each server request

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#64]
**Summary:**  
For every request that Salt Edge Authenticator performs to the server, it is necessary to additionally provide some important information for the Audit log.

**Task:**  
- [ ] Add the User agent request header (application and version) for all REST requests
- [ ] Add the User agent request header (application and version) for WebView requests
- [ ] Update documentation and examples.

**Comment by ConstantinKV** [comment]
good example https://github.com/danielceinos/Cooper/blob/master/cooper/src/main/java/com/danielceinos/cooper/CooperInterceptor.kt

**Comment by ConstantinKV** [comment]
```wkWebView.customUserAgent = "IOS agent"```
