### ISSUE TITLE
Application UX/UI redesign

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#87]
## **Summary:**  
The app design should be unique, fresh, modern, bring comfort and ease at usage - that's why we need redesign to enhance these parameters. So, taking all these factors, it was decided to start redesign process, before are implemented new features.   

Design will be covering 2 modes: Standard (bright/white) mode and Dark (night/black) mode

___

## **Design:**  
https://www.figma.com/file/G6Jnrm2KBwHH5FelsVrLcR/Authenticator-Redesign?node-id=178%3A3008

___

## **Tasks:**  

**1. Splash screen**  

- [x] Brand logo - screen 1:
  - Simple standard splash screen with Authenticator logo, brand name, and Salt Edge logo in the bottom. As discussed, you can consider to apply it as an image if this is a good way of improvement.
<details>
  <summary><b>Screenshot:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/78354048-cdc42100-75b3-11ea-90eb-acf1a476427d.png)

</details>

___

**2. On-boarding screens**  

The first time when application is opened, after the splash screen user is taken to the on-boarding screens with general information on the application
- [x] Onboarding - screen 1:
  - Summary: First page with info on "Scan QR to connect to provider"
  - Title: "Use QR codes"
  - Description: "Asked to scan QR? Tap QR button to use the quick QR code scanner and take action."
  - Actions: "Skip" button takes user directly to the passcode setup; "Next" button takes user to the second onboarding page
  - _Picture: Use the picture from design_
- [x] Onboarding - screen 2:
  - Summary: Second page with info on "How to authorize actions"
  - Title: "Full control"
  - Description: "Made transaction? You will get push notification. Open application, verify the transaction details, and simply authorize your actions."
  - Actions: "Skip" button takes user directly to the passcode setup; "Next" button takes user to the third onboarding page
  - _Picture: Use the picture from design_
- [x] Onboarding - screen 3:
  - Summary: Third page with info on "Application Security"
  - Title: "Ultimate security"
  - Description: "Strong customer authentication brings additional security to your payments, diminishing possibility of fraudulent activity."
  - Actions: When switched to the third page, button "Next" from the previous page lengthens and becomes wide with name "Get started". Button "Get started" takes user to the passcode setup.
  - _Picture: Use the picture from design_
<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/82234491-2a985280-993a-11ea-9673-6d66c2f862c4.png)

</details>

___

**3. Passcode setup** 

- [x] Passcode insert - screen 1:
  - Title: "Create passcode"
  - Actions: user has to insert 4-digit passcode. After this user will be taken to "repeat passcode" page automatically.
- [x] Passcode repeat - screen 2:
  - Title: "Confirm passcode"
  - Actions: user has to repeat the 4-digit passcode. If successful, user will be taken to "Scan QR - first" page automatically.
- [x] Passcodes don't match - screen 3:
  - Notification message text: "Passcodes don't match"
  - Actions: if user has made a mistake on "Repeat passcode" page, user will be taken back to the "Create passcode" page, with an informative message appeared "Passcodes don't match".
  - Additional: after what passcode was incorrectly introduced the second time, the filled circles twitch and user should feel light vibration.
- [x] Allow notifications - screen 4:
  - Actions: after successful passcode setup, user should be asked at this point by the system to "allow notifications". Once user allows notifications (or if denies), user will be taken to "Scan QR - first" screen automatically (screen 5).

<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/81158156-5f96c380-8f90-11ea-97bf-48f0c2e29247.png)

</details>

___

**4. Scan QR code screens** 

- [x] Scan QR - first - screen 1:
  - Title: "Scan QR code"
  - Description: "Scan the QR to make your first connection"
  - Action: The scanner with this specific text launches right after on-boarding (after what user allow notifications, he is asked about camera permission and this screen is launched). If user taps on "Cancel" button, he is taken to the main page (Authorizations), where the empty state also tell that there are no connections (screen 1 from task 5). If user launches QR scanner from app via QR icon or button "Connect", then this page opens with this specific text
  - Note: if user connects via Deep Link, QR code scan page will not be necessary after on-boarding, if user did not pass on-boarding yet.
- [x] Scan QR - standard - screen 2:
  - Title: "Scan QR code"
  - Description: "Scan the QR code to take action"
  - Action: The scanner with this specific text launches when there already is a connection - launches from the QR icon/button or the "Scan QR" button on main page. If user taps on "Cancel" button, he is taken to the standard main page (Authorizations), with the empty state "no authorizations" (screen 2 from task 5).
<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/78991672-265e6580-7b42-11ea-850b-f0180a68a83d.png)

</details>

___

**5. Authenticator (main page) screens** 

- [x] No connection state (with button to trigger action) - screen 1:
  - Summary: Main Authenticator page - if no connections are present, need to show this page with button "Connect" to trigger first connection for user.
  - Header: "Authenticator"
  - Title: "No connections"
  - Description: "Seems like you didn’t connect to your provider yet. Add new connection to securely authorize your actions."
  - Picture: _Use the picture from design_
  - Actions: Button "Connect" launches for user the Scan QR - first (screen 1 in task 4), for user to make the first connection. Icon "QR" is a button to trigger the QR code scanner, and if no connections are present - launches same QR scan page as "Connect" button. 
- [x] Empty state - screen 2:
  - Summary: Main Authenticator page - if user already has connected a bank, in this page are expected (being polled) the "authorization requests". Need to show this page as a default one when there are present connections.
  - Header: "Authenticator"
  - Title: "Nothing to authorize"
  - Picture: _Use the NEW picture from design_
  - _Description: "You don’t have any active authorization requests yet. **Scan QR code** for instant action or to connect new provider."_
  - Actions: Icon "QR" _and "Scan QR"_ are buttons to trigger the QR code scanner - Scan QR standard page (screen 2 in task 4).
- [x] Drop-down menu - screen 3:
  - Summary: The icon "3 dots" is a button to launch the menu with currently only 2 options: "View connections", "Go to settings". Button "Cancel" or tap away from buttons will close the menu. The rest of screen is dimmed when menu opened.

<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/82240595-58ce6000-9943-11ea-86aa-bd971b22a098.png)

</details>

___

**6. Unlock flow screens** 

On application unlock - app first is always asking for the TouchID/FaceID input (system biometric input is triggered). If user cancels it, then he sees first screen with Passcode.

- [x] Passcode - screen 1:
  - Summary: This is the first Passcode screen user sees if biometric input is canceled. On this screen user did not insert anything yet. User has the insert buttons with digits in the bottom, with 2 actions.
  - Actions: The "Fingerprint" icon is a button that triggers again the Biometric input window. The "Forgot?" is a button that opens "Forgot passcode?" page.
- [x] Typing passcode - screen 2:
  - Summary: This screen represents the behavior when user is already inputting some passcode digits. The circles fill with blue color once a digit is input.
  - Actions: Once user inputs first digit, the "Fingerprint" icon changes to the "Delete" icon to empty the input digits. If user empties the digits, it transforms back to "fingerprint" icon. The "Forgot?" is a button that opens "Forgot passcode?" page.
- [x] Wrong passcode - screen 3:
  - Summary: If user has inserted wrong passcode, a small pop-up message appears with text "Wrong passcode", the filled circles become empty, twitch, and user should feel light vibration. The "Delete" icon changes to the "Fingerprint" icon.
  - Actions: The "Fingerprint" button triggers again the Biometric input window. The "Forgot?" button that opens "Forgot passcode?" page.
- [x] Forgot passcode? - screen 4:
  - Summary: If user has forgot his passcode, he can open this page and restore app to default settings by tapping on "Clear data".
  - Title: "Forgot passcode?"
  - Description: "Please clear app data and establish new connection with your provider."
  - Picture: _Use the picture from design_
  - Actions: "Clear data" button triggers the flow to restore the app to it's default settings, but first triggers the confirmation step "Clear app data?" (screen 5). The "Back" icon is a button that takes user back to the first passcode unlock page.
- [x] Confirm Clear app data - screen 5:
  - Summary: A confirmation step is an important step so that user does not accidentally deleted all the info on the app.
  - Title: "Clear app data?"
  - Description: "All app data including connected  providers, user data and settings will be  permanently deleted"
  - Actions: "Cancel" button cancels the flow and closes the window, same does any tap on the screen. "Clear" button - deletes all info from app and user should start from the on-boarding.

<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/82549672-f608de80-9b65-11ea-9e47-cd2931599d58.png)

</details>

___

**7. Enrollment screens (QR/Deep Link)** 

The enrollment flow starts with either QR code scan, or with Deep Link that user activates. So, if user has to scan the proposed QR code, then he goes to the Authenticator main page taps on "QR" icon or "Connect" button (screen 1) in case it's first connection and specific QR scanner launches (screen 2). If it is not the first connection, user has to tap on "QR" icon or "Scan QR" button on main page, and launches the "QR scan - standard" page.
- [x] WebView - screen 3:
  - Summary: the WebView page is launched with header "New connection" after what the QR code is scanned for user to authenticate on provider side.  In case of Instant Enrollment, this page is skipped.
  - Actions: Display WebView, and "Cancel" button will cancel the enrollment flow and take user to the main page.
- [x] Processing - screen 4: _NEW POINT_  
  - Summary: when the enrollment is in process, after what user was authenticated (or scanned QR with connect_query for instant enrollment), this processing state is displayed with "loading" animated spinner.
  - Title: "Processing"
  - Description: "This may take some time"
  - Actions: This action cannot be interrupted, thus there are no actions available (only kill app).
- [x] Connection status "success" - screen 5:
  - Summary: if the enrollment flow is finished successfully, app should display this page with header "New connection" and with successful status message and indicate the provider name
  - Title: "{Provider name} was successfully connected"
  - Description: "You will receive an authorization request every time you make an action."
  - Picture: use successful state icon from design
  - Actions: "Done" button takes user to the "Connections" page to show the list of connection.
- [x] Connection status "fail" - screen 6:  
  - Summary: if the enrollment flow is finished with an error, app should display this page with header "New connection" and with failure status message and also indicate the provider name
  - Title: "{Provider name} connection failed"
  - _Description: "Error occurred. Please try again later or contact support."_
  - Picture: use fail state icon from design
  - Actions: "Retry" button takes user to the beginning of the flow - "Scan QR" page. "Close" button takes user to the main page.

<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/82313717-6af6df80-99d1-11ea-8849-52d9f5c277e1.png)

</details>

___

**8. Connections screens** 

- [x] Empty state - screen 1:
  - Summary: empty state page with header "Connections" is displayed if there are no connected providers. Message tells about what user has to do.
  - Title: "No connections"
  - Description: "Seems like you didn’t connect to your provider yet. Add new connection to securely authorize your actions."
  - Picture: _Use the picture from design_
  - Actions: 'Connect" button launches the QR scan - first time with specific text. "Back" button takes user to the main page.
- [x] Provider connected state - screen 2:
  - Summary: this page shows a list of connected providers with provider name and datetime when provider was connected.
  - Status: by template: "Connected on D(DD) MMM YYYY", where D(DD) = 1-31, MMM = "Jan"/"Feb"/etc., YYYY = 2019/2020/etc,
  - Actions: "Back" button takes user to the main page.
- [x] Provider inactive state - screen 3:
  - Summary: on this page are displayed examples of the multiple connections and "Inactive" state of provider
  - Status: "Inactive. Please reconnect."
  - Actions:  "Back" button takes user to the main page.
- [x] Provider connected - drop-down menu - screen 4:
  - Summary: this is the example of the provider's menu (options) when connection is stable, initiated by long-tap. After long tap provider card is highlighted, background is blurred.
  - Icons: please use icons from design
  - Actions:
    - "Rename" option will start the provider rename process. Please use the native "Rename" UI in accordance with the new design.
    - "Contact support" will launch the "compose email" page with predefined receiver. Please use the native "Contact support" UI (open default mail client).
    - "Delete" button as a result will delete the provider, with additional confirmation step (screen 6). Confirmation step has header "Delete connection", text "Are you sure you want to delete connection to your service provider? This action cannot be undone." and 2 button: "Cancel" and "Delete"
    - Tap away from the menu will close the menu.
- [x] Provider inactive - drop-down menu - screen 5:
  - Summary: this is the example of the provider's menu (options) when connection is inactive (revoked from server side), initiated by long-tap. After long tap provider card is highlighted, background is blurred.
  - Icons: please use icons from design
  - Actions: 
    - "Reconnect" will launch the enrollment flow - authentication page, taken from the "Connection". The pages in the reconnect flow have everything the same except the pages header, which should be "Reconnect" (instead of "New connection").
    - "Rename" option will start the provider rename process. Please use the native "Rename" UI in accordance with the new design.
    - "Contact support" will launch the "compose email" page with predefined receiver. Please use the native "Contact support" UI (open default mail client).
     - Here, if provider is inactive, the "Delete" option changes to "Remove" because the connection is already revoked. "Remove" option will delete the provider instantly from list, with NO additional confirmation step.
    -  Tap away from the menu will close the menu.

<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/81165794-45aeae00-8f9b-11ea-8079-508557fc9bb9.png)

</details>

___

**9. Authenticator main page - Authorizations screens** 

The switch from the empty state to the authorization request should be animated, not an instant swap.

- [x] Single authorization - screen 1:
  - Summary: design update, keep exactly the same functionality
- [x] Multiple authorizations - screen 2:
  - Summary: design update, keep exactly the same functionality
- [x] Authorization processing state - screen 3:
  - Summary: design update, keep exactly the same functionality
  - Title: "Authorizing"
  - Description: "Please wait while authorization is processing"
- [x] Authorization confirmed state - screen 4:
  - Summary: design update, keep exactly the same functionality
  - Title: "Success"
  - Description: "Your action was successfully authorized"
- [x] Authorization denied state - screen 5:
  - Summary: design update, keep exactly the same functionality
  - Title: "Denied"
  - Description: "Your action was denied"
- [x] Authorization error state - screen 6:
  - Summary: design update, keep exactly the same functionality
  - Title: "Something went wrong"
  - Description: "Please try again"
- [x] Authorization time expired state - screen 7:
  - Summary: design update, keep exactly the same functionality
  - Title: "Time out"
  - Description: "Time to authorize the action is out"
- [x] Authorization unavailable state - screen 8:
  - Summary: pop-up message with the empty state on the background or empty authorization request. Updated design.
  - Title: "Authorization unavailable"
  - Description: "Authorization request was either processed, canceled or expired."

<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/81280053-a227d100-9060-11ea-9a66-5c4c412b8c3f.png)

</details>

___

**10. Settings screens** 

- [x] Available settings - screen 1:
  - Title: "Settings"
  - Actions: "Back" button takes user to the "Authenticator" main page.

Below are described Settings and their functions  
- [x] "General" settings: "Change passcode" screens 2-6:
  - Title: "Change passcode"
  - Actions: "Back" button takes user to the "Settings" main page. "Backspace" button in the digits keyboard removes the inserted digits.
  - (2) Step 1: "Your current passcode" - user has to introduce a 4-digit passcode
  - (3) Step 2: "New passcode" - after successful confirmation of current passcode, user has to create new 4-digit passcode
  - (4) Step 3: "Confirm passcode" - user has to confirm the new passcode
  - (5) Incorrect "Confirm passcode": if user repeats the passcode and is wrong - take user back to "New passcode" page and display the pop-up warning "Passcodes don't match" (2 sec).
  - (6) Incorrect "Your current passcode": if user has introduced incorrect current passcode when he wanted to change passcode, just erase the inserted digits and display the pop-up warning "Wrong passcode" (2 sec).
- [x] "General" settings: "Language":
  - Please add simple native picker from list - in accordance with design
- [x] "General" settings: "Face ID" / "Touch ID":
  - Depending on the device type, user can disable or enable from this page the biometric input on unlock flow.
- [x] "Info" settings: "About":
  - Please add simple native page with same functionality as now - in accordance with design
- [x] "Info" settings: "Report a bug":
  - Please add simple logic to send email with predefined email address
- [x] Additional option: "Clear all data" and confirmation step - screen 7:
  - Title: "Clear app data"
  - Description: "App data including connected providers and user data will be permanently deleted"
  - Actions: "Cancel" button cancels the action. "Clear"button confirms the action and everything is deleted. User is kept on same page.

<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/82547232-0dde6380-9b62-11ea-9a0d-9ac0b272b321.png)

</details>

___

**11. Instant action screens (QR/Deep Link)** 

Instant Action logic has changed a little. There cannot be an Instant Action without an authorization request. Hence, now Instant Action has it's own authorization details page to confirm authorization. The present final statuses where there was no Authorization request are eliminated because are not needed.

Instant action flow starts with the main page (screen 1) from which user launches QR scanner (screen 2) and eventually scans a specific QR code. If Deep Link is activated, then start with next step.

- [x] Choose connection - screen 3-4:  
  - Summary: Opens only when user has 2 SIMILAR connections (same provider/same connect_url). when connection is selected, the connection card is highlighted. Card itself is similar to the connection card on "Connections" page. 
  - Header: "Choose connection"
  - Actions: "Cancel" button cancels the action and user is taken back to main page. "Proceed" button is disabled until user chooses a certain connection. "Proceed" button becomes active when connection is selected. 
- [x] Processing - screen 5:  
  - Summary: when the Instant Action is processing, after what user scanned Instant Action QR, this processing state is displayed with "loading" animated spinner.
  - Header: "New action"
  - Title: "Processing"
  - Description: "This may take some time"
  - Actions: This action cannot be interrupted, thus there are no actions available (only kill app).
- [x] Authorization details page - screen 6:  
  - Summary: Same as Authorization details page, please apply the final statuses logic.
  - Header: "New action"
  - Actions: "Close" button closes the flow and user is taken to the main page.
- [x] No authorization returned - screen 7:  
  - Summary: Same as Authorization details page, please apply the final statuses logic.
  - Header: "New action"
  - Title: "Something went wrong"
  - Description: "Error occurred. Please try again later or contact support."
  - Actions: "Done" button closes the page and user is taken to the main page. 
<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/82556937-62d6a580-9b73-11ea-8e83-450eed89702d.png)

</details>

**12. Additional screens/states** 

- [x] No internet connection - screen 1:
  - Summary: When there is lost internet connection - it affects only the "Authenticator" main page, where are displayed authorizations. Hence, we change the empty state (or if there is authorization request present, then also) to the No internet state with new picture, title and description. Please apply smooth animation for state change.
  - Title: "You're offline"
  - Description: "Your network is unavailable. Please verify your internet connection."
- [x] App 1 minute lock - screens 2:
  - Summary: for the redesign we cannot apply the same warning as we had in previous version, that is why a new type of notification should be applied. Please verify the design with colors for light/dark mode. Notification should appear from the bottom. Keep same rules as present now. On cancel or any tap on screen (some activity) - app is not going lock anymore.
  - Notification text: "Application will be locked due to inactivity" with an "info" icon. 
- [x] App block due to incorrect passcode - screen 3:
  - Summary: when user inserts passcode for many times in a row - incorrectly, the app due to security reasons should be locked for certain time. I propose new way to lock the app, taking into consideration that user might require the app to confirm his certain action: 1) 5 bad attempts = 1 minute block, 2) 1 bad attempt after = 3 minutes block, 3) 1 bad attempt after = 5 minutes block, 4) repeat last step.
  - Text for 1 minute: "You entered wrong passcode. Please try again in 1 minute."
  - Text for 3 minutes and above: "You entered wrong passcode. Please try again in 3 minutes."
  - Please apply the iOS style design as it is now, but it should be according to the redesign or light/dark mode colors. There are no actions user can do besides killing the app.

<details>
  <summary><b>Screenshots:</b></summary>

![image](https://user-images.githubusercontent.com/38658558/83537694-92839700-a4fd-11ea-810d-91da4529a4d4.png)

</details>

___

**13. Extra check** 

- Enabling dark theme in iOS WebViews
- Navigation between the screens (slide-in/slide-out/push/instant/etc)
- Blur

___

Thank you!

**Comment by AlexLobaciov** [comment]
All done
