### ISSUE TITLE
Authorizations status update

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-ios#9]
**Summary:**  
`We need to adjust the statuses of the each authorization, so that customer has clear understanding of what is going on with authorization, after the "Allow"/"Deny" action.`

**Design:** https://www.figma.com/file/DUgnsLqq0Sg2sebofP61MZ/Auth-V2---iOS?node-id=0%3A620

**Task:**  
For "Authorizations" page keep in mind that there is an extra step - confirmation with Touch ID/Face ID/Passcode. Also, if app is opened via push notification, app just searches for the exact authorization from list and shows it no matter where it is in the list.
- [x] 1) Screen 1: After what customer pressed on either "Allow" or "Deny", the whole authorization should freeze, authorization becomes "in progress" and app is waiting for the final status. While "in progress" -  background is blurred, the "spinner" is displayed, "Authorizing..." title and description "Please wait while authorization is processing" are shown.
- [x] 2) Screen 2: If customer pressed "Allow", successful status is shown when action was successfully processed by Service Provider. Once "Allowed", background is still blurred, the "spinner" is changed to icon with "check-mark", title should be "Success" and description: "Your action was successfully authorized".
- [x] 3) Screen 5: If customer pressed "Deny", deny status is shown when action was successfully processed by Service Provider. Once "Denied", background is still blurred, the "spinner" is changed to icon with "minus" sign, title should be "Denied" and description: "Your action was denied".
- [x] 4) Screen 3: If customer pressed either "Allow" or "Deny" and process was NOT processed by Service Provider, meaning that we've received an error, then: background is still blurred, the "spinner" is changed to red icon with "exclamation mark" sign, title should be "Something went wrong" and description: "Please try again".
- [x] 5) Screen 4: If customer DID NOT press either "Allow" or "Deny", the process is finished for Service Provider, the whole authorization should freeze and background is blurred, the "time out" icon is displayed, together with "Time out" title and description "Time to authorize the action is out".

Additionally:
- [x] 6) When the final state of authorization is available, it should automatically close in 3 seconds.
- [x] 7) "Authorization unavailable" message should be displayed if customer reacted on authorization by just entering the app, and then opened the push-notification (after some time) and app could not find necessary authorization.

**Logic behind the authorizations list:**  
- We will use LILO approach - Last In > Last Out, taking into consideration already existing in list authorizations.
- When authorization gets to the list, it holds a position, for example, we have 5 authorizations from 2 providers that came in from polling when we opened application, namely "1.1", "1.2", "1.3", "2.1", "2.2". When in next 2 seconds we refresh the list, they can come into different, chaotic order, like: "1.2", "1.3", "1.1", "2.2", "2.1". The list should not renew it's order, just update the content, in case there are any changes. Logic should verify whether there are new authorizations and put them in the end of the list. In case while getting updated list of authorizations from polling, the app cannot find an authorization from the list that is displayed to customer, then the missing authorization just disappears.
To cover all cases, for example we already have in list the following authorizations: "1.1", "1.2", "1.3", "2.1", "2.2". Now, user has confirmed authorization "1.1", authorization "2.1" was confirmed in another app, and there are 2 new incoming authorizations from polling. As a result we have new incoming list, namely: "2.2", "2.3", "1.4", "1.3", "1.2", "3.1", so the final list will look for customer as following: "1.2", "1.3", "2.2", "2.3", "1.4", "3.1".

**Screenshot**  
![image](https://user-images.githubusercontent.com/38658558/64439042-d0b86b00-d0d1-11e9-849f-38317315abee.png)

Authorization unavailable:  
![image](https://user-images.githubusercontent.com/38658558/64440108-0fe7bb80-d0d4-11e9-8dd6-aa96485df973.png)

**Comment by AlexLobaciov** [comment]
@ConstantinKV @baller784 you can proceed

**Comment by AlexLobaciov** [comment]
@baller784 please proceed with this issue. It's the current focus.

**Comment by AlexLobaciov** [comment]
@baller784 

1) The "Loading" spinner is not according to the design. Please adjust.
2) Success message has mistake "Ypur" > change to > "Your", and please remove the dot (".") from the end of the sentence
3) "Time out" status - please remove the dot (".") from the end of the sentence "Please try again"
4) Sometimes it happens that the Final status is not being automatically closed after 3 seconds. Happens especially with the "Something went wrong" status. I have "Allowed" the action and simultaneously deleted connection, which resulted in this status. Please check, as the final status is actuall
5) If I have 4 authorizations, and I'm on 3rd, and the first one in position expires, I stay at 3rd position, but authorization request changes to the one that was 4th one in list. So, I stay on 3rd position, rather than stay on the specific authorization request.

All else is good! Just some small adjustments please.
